// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "b5a0ce3b-e567-49c6-8d64-d5a5cf43eb45";
const char DEVICE_LOGIN_NAME[]  = "b315208d-601b-4ca0-8131-93a50977e72b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSetTemperatureChange();
void onSeasonBtnChange();

float setTemperature;
float currentTemperature;
bool isActive;
bool seasonBtn;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(setTemperature, READWRITE, ON_CHANGE, onSetTemperatureChange);
  ArduinoCloud.addProperty(currentTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(isActive, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(seasonBtn, READWRITE, ON_CHANGE, onSeasonBtnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
